source 'https://rubygems.org'
gem 'byebug'
#gem 'catalog-api-client-ruby', '~> 1.0.0', :git => 'https://github.com/syncrou/catalog-api-client-ruby.git'
gem 'catalog-api-client-ruby', '~> 1.0.0', :path => '~/syncrou/catalog-api-client-ruby'
gem 'optimist'
